//
//  struct.swift
//  HW3_bindingapp
//
//  Created by 陳政沂 on 2020/11/2.
//

import Foundation

struct Songs {
    var song_name: String
    var signer: String
    var lyrics: String
    var grade: Double
    var music: String
    var pic: String
}

let Jay_songs = [
    Songs(song_name: "告白氣球", signer: "周杰倫", lyrics: "塞納河畔 左岸的咖啡\n我手一杯 品嚐你的美\n留下唇印的嘴\n\n花店玫瑰 名字寫錯誰\n告白氣球 風吹到對街\n微笑在天上飛\n\n你說你有點難追 想讓我知難而退\n禮物不需挑最貴 只要香榭的落葉\n營造浪漫的約會 不害怕搞砸一切\n擁有你就擁有 全世界\n\n親愛的 愛上你 從那天起\n甜蜜的很輕易\n親愛的 別任性 你的眼睛\n在說我願意", grade: 5.0, music: "zhou-jie-lun-jay-chou-te-bie-yan-chu-pai-wei-jun-gao-bai-qi-qiu-love-confession-official-mv", pic: "告白氣球"),
    Songs(song_name: "等你下課", signer: "周杰倫", lyrics: "你住的巷子裡\n我租了一間公寓\n為了想與你不期而遇\n高中三年 我為什麼\n為什麼不好好讀書\n  沒考上跟你一樣的大學\n\n我找了份工作\n離你宿舍很近\n當我開始學會做蛋餅\n才發現你不吃早餐\n\nWo 你又擦肩而過\n你耳機聽什麼\n能不能告訴我\n\n躺在你學校的操場看星空\n教室裡的燈還亮著你沒走\n記得我寫給你的情書\n都什麼年代了\n到現在我還在寫著\n\n總有一天 總有一年 會發現\n有人默默的陪在你的身邊\n也許我不該在你的世界\n當你收到情書\n也代表我已經走遠\n\n學校旁的廣場\n我在這等鐘聲響\n等你下課一起走好嗎\n彈著琴唱你愛的歌\n暗戀一點都不痛苦\n痛苦的是你根本沒看我\n\n我唱這麼走心\n卻走不進你心裡\n在人來人往找尋著你\n守護著你 不求結局\n", grade: 4.0, music: "zhou-jie-lun-jay-chou-with-yang-rui-dai-deng-ni-xia-ke-waiting-for-you-ge-ci-ban-mv", pic: "等你下課"),
    Songs(song_name: "不愛我就拉倒", signer: "周杰倫", lyrics: "寒流來了 剛好\n剛好可以 把你手放外套\n把安全帽戴好\n不讓你在 愛情路上跌倒\n\n加速狂飆 你說不要\n愛的險你不想冒\n不想被套牢\n他的懷抱 真比我好\n你幸福就好\n\n不愛我就拉倒\n離開之前\n不要愛的抱抱\n反正 我又不是沒有人要\n哥練的胸肌\n如果你還想靠\n好膽你就麥造\n寒流來了 剛好可以 把你手放外套\n把安全帽戴好 不要在愛情路上跌倒\n加速狂飆 你 你說不要\n愛的險你不想冒 不想被我給套牢\n反正我又不是沒有人要\n哥練的胸肌如果你還想靠\n算了 你幸福你幸福就好", grade: 3.0, music: "zhou-jie-lun-jay-chou-bu-ai-wo-jiu-la-dao-if-you-dont-love-me-its-fine-official-mv-fa-shao-ying-pian-hua-yu-di-qu-chan-lian-di-mei-guo-zhi-chong-qian-er", pic: "不愛我就拉倒"),
    Songs(song_name: "說好不哭", signer: "周杰倫", lyrics: "沒有了聯絡 後來的生活 我都是聽別人說\n說妳怎麼了 說妳怎麼過 放不下的人是我\n人多的時候 就待在角落 就怕別人問起我\n你們怎麼了 妳低著頭 護著我連抱怨都沒有\n\n電話開始躲 從不對我說 不習慣一個人生活\n離開我以後 要我好好過 怕打擾想自由的我\n都這個時候 妳還在意著 別人是怎麼怎麼看我的\n拼命解釋著 不是我的錯 是妳要走\n\n眼看著妳難過 挽留的話卻沒有說\n妳會微笑放手 說好不哭讓我走\n妳什麼都沒有 卻還為我的夢加油\n心疼過了多久 還在找理由等我", grade: 2.0, music: "zhou-jie-lun-jay-chou-shuo-hao-bu-ku-wont-cry-with-wu-yue-tian-a-xin-mayday-ashin-official-mv", pic: "說好不哭"),
    Songs(song_name: "不該", signer: "周杰倫", lyrics: "假裝我們還在一塊 我真的演不出來\n還是不習慣你不在 這身份轉變太快\n畫面裡不需要旁白 卻誰都看得出來\n是我情緒湧了上來 想哭卻一遍空白\n\n雪地裡相愛\n他們說 零下已結晶的誓言不會壞\n但愛的狀態\n卻不會永遠 都冰封而透明的存在\n\n輕輕飄 落下來\n許下的夢 融化得太快\n或許我們都不該醒來\n\n你還是住在我的回憶裡 不出來\n讓我們微笑離開 讓故事留下來\n放手後 愛依然在\n雪融了 就應該化開\n緣若盡了 就不該再重來\n\n你依舊住在我的回憶裡 不出來\n我離開將你的手交給 下個最愛\n糾纏與固執等待 反而是另一種傷害\n彼此緊握的手鬆開 去擁抱更多未來\n\n錯過的時間怎麼買 誰都付不出來\n或許我們學會釋懷 讓過去安靜下來\n\n雪地裡相愛\n他們說 零下已結晶的誓言不會壞\n但愛的狀態\n卻不會永遠 都冰封而透明的存在\n\n輕輕飄 落下來\n許下的夢 融化得太快\n或許我們都不該醒來", grade: 1.0, music: "zhou-jie-lun-jay-chou-x-amei-bu-gai-shouldnt-be-official-mv", pic: "不該")]

let Eso_songs = [
    Songs(song_name: "Change", signer: "瘦子Ｅ.SO", lyrics: "I don’t wanna change you baby\nPlease don’t try to change me baby\nWe loved each other in the first place\n現在我們要的是誰\nSee I don’t wanna change you baby\nPlease don’t try to change me baby\n繞了一圈回到原點\n要不乾脆換另一位\n妳沒有說話總是低著頭\n形同陌路卻還是牽著手\n一朵浮雲我卻想要抓的攏\n空氣凝結身邊的路人都變成兵馬俑\n\n妳曾經問我 怎樣才算perfect match\n我沒有跟妳說過在我見妳第一面\n如今我更不確定 妳想要的改變\n我能不能不當妳家人想要的圖片\n\n我每天對著鏡子練習\n襯衫的扣子需要扣到哪裡 才算得體\n車裡的音樂清單換掉了 再會了陷阱\n我只有國中畢業證書是否不夠配妳\n\nBaby you don’t need to change\nI don’t feel no shame\n我不需要妳的任何改變我深愛著妳是誰\n\nI’m sorry I was panic以為這樣才是對\n忘記什麼讓我們能快樂但自私在作祟\n\nI don’t wanna change you baby\nPlease don’t try to change me baby\nWe loved each other in the first place\n現在我們要的是誰\nSee I don’t wanna change you baby\nPlease don’t try to change me baby\n繞了一圈回到原點\n要不乾脆換另一位\n\n改我的態度\n因為妳只想要當妳\n會讓妳哭\n如果我只做我自己\n都是敗訴\n兩個人只保護自己\nI can’t save you I can’t blame you\n\n把脖子掐的太緊\nWanna run away\n妳的問題像猜燈謎\n不敢隨便回\nYou say you hate me but you love me\ngetting complex\nYou say you hate me but you love me\n哩勒公蝦毀\n\n燒好的菜 卻食之無味\n話題不再 幽默當消遣\nBaby it’s fine\n不算太壞 感覺能找回來\n燒好的菜 卻食之無味\n話題不再 幽默當消遣\nBaby it’s fine\n不算太壞 感覺能找回來\nI don’t wanna change you baby\nPlease don’t try to change me baby\nWe loved each other in the first place\n現在我們要的是誰\nSee I don’t wanna change you baby\nPlease don’t try to change me baby\n繞了一圈回到原點\n要不乾脆換另一位\n" , grade: 5.0, music: "shou-zi-e-so-change-official-music-video-5k", pic: "change"),
    Songs(song_name: "Wait", signer: "瘦子Ｅ.SO", lyrics: "我需要你的助力像是在盪鞦韆\n這次我的心裡終於沒有糾結\n二手車的經歷雖然他老舊點\n挺你還算容易後座還有座位\n\n天災人禍 只怕一開始就沒真的站穩\n上帝給我的考驗不是全都贊成\n我自認我沒那麼偉大當一個善人\n我殺掉那些敵人是我能夠做到的忠誠\n\n說真的\n從來沒有懷疑過\n對自己有多少容忍\n才能清楚凡人偶爾會脆弱\n\n那道溫暖它從 東 邊 在 升 起\n燃 燒 我的生命 留 下 的痕跡 能讓孩子看著\n範 本 在 複 習 最後能夠 成就 G R E A T\n\nDon’t you tell me you should\nwait wait wait wait wait\n恁爸頭髮都要白\nYou can’t stop the\ngreat great great great\nGreatness 註定要到來\nMotherfucker I’m gonna\ntake take take take take\n城市裡的羅賓漢\nI will pay pay pay pay pay\n那些辛苦的血汗\n\nLike Khaled\nMajor key\n不是誰都能拿\n在追人氣\n沒意義\n隨時都會蒸發\nThrow some D’s\nOn that bitch\n滿足不了生涯\n替自己辦的成年禮這場面多麼盛大\n我告訴小夥子的忠告 沒有一個人在聽\n也對 我在他這個年紀can’t tell me nothing\n不屑 I wish you all the best\n有天你會體會\n始終got you back 願你不被擊退\n在家叼著煙 counting million dollar bills\n有天讓敵人能為你加油\n兄弟離開gang 不用血染雙手\nWe survive 那道溫暖它從 東 邊 在 升 起\n燃 燒 我的生命 留 下 的痕跡 能讓孩子看著\n範 本 在 複 習 最後能夠 成就 G R E A T\n\n", grade: 4.0, music: "shou-zi-e-so-wait-official-music-video", pic: "wait"),
    Songs(song_name: "她沒在看我", signer: "瘦子Ｅ.SO", lyrics: "最遠的距離我們之間多了他\n5.58 inches 擋著妳的眼神沒有紮\n我想記得妳的樣子有點面熟 I mean\n我的線索都是半張臉孔 有點籠統\n我以為妳會期待我們見面\n我以為我們能夠認識不只有夢裡的畫面\n或許妳害怕交談只留下一張照片\n我離開時還在想是否我的奢望有點越線\n我想 看妳跳舞 我想 看妳身體讚美我的天賦\n讓我感覺不是獨處 妳能鼓舞 我想看妳笑的開懷像妳愛妳生命妳笑的開懷像妳愛妳生命永遠都是春季 香甜可口蜂蜜\n把手給我 讓我握著\n我讓妳感受那些我不曾有過的\n這是唯一能讓妳看到我的方法 或者\n\n2019有沒有時光機能夠坐呢\n\n她沒在看我 她沒在看我\n在她的心中 卻有一半我\n每當我低頭 她沒在舞動\n當我揮灑著汗水 當我揮灑汗水\n\n當我的視線跟他對到眼\n當我的思緒沒法安份點\n幾千隻雙眼盯著我們的關係都無法輕淡寫\nOh man 那畫面散太遠\n我記得 妳那天遞給我的一張面紙\n留著妳的電話 妳的地址 妳的意思\n我躺在房裡想著妳撫媚的樣子\n抱歉我不能出現\n他還在妳照的那面鏡子\n他在那記錄妳的妝容妳的胖瘦\n今天晚上妳會遇見誰\n陪伴妳的每個週末 妳的放縱\n留給我的已經不特別\n為何他總是讓妳低頭\n不停想我就算我已站在妳面前\n剩下留給妳的腦中 妳的眼中\n哪怕只有一瞬間\n\n她沒在看我 她沒在看我\n在她的心中 卻有一半我\n每當我低頭 她沒在舞動\n當我揮灑汗水 當我揮灑汗水\n\n他在那記錄妳的妝容妳的胖瘦\n今天晚上妳會遇見誰\n陪伴妳的每個週末 妳的放縱\n留給我的已經不特別\n為何他總是讓妳低頭\n不停想我就算我已站在妳面前\n剩下留給妳的腦中 妳的眼中\n哪怕只有一瞬間", grade: 3.0, music: "shou-zi-e-so-ta-mei-zai-kan-wo-she-aint-watchin-official-music-video-5k", pic: "她沒在看我"),
    Songs(song_name: "伯父", signer: "瘦子Ｅ.SO", lyrics: "伯父他不愛 他不愛我整手刺青\n他特別不愛 我一個太自由的心\n\n伯父他不愛\n做的音樂沒出息\n\n伯父他不愛我所有的理由\n氣我搶走他的Babe Girl\n\n是我不太懂事 是我太雞婆\n你別花家裡的錢 以後你都花我\n          伯父不太喜歡我又搶了他工作\n他說沒有人能愛他女兒比他多\n抱歉 我們今天晚上玩到三更半夜 My Bad\n兩人世界容易忘記時間 Always\n我是該讓她在家裡多點\n伯父不喜歡我叫他寶貝女兒搖落\n\n          伯父他不喜歡壞的男生\n他不知道他的女兒品味獨特\n討厭我的工作我的出身\n沒有好的學歷 家世顯赫\n\n伯父他不喜歡壞的男生\n他不知道他的女兒品味獨特\n討厭我的工作我的出身\n沒有好的學歷 家世顯赫\n\n伯父他不愛 他不愛我整手刺青\n他特別不愛 我一個太自由的心\n伯父他不愛\n做的音樂沒出息\n\n伯父他不愛我所有的理由\n氣我搶走他的Babe Girl\n\n不是伯父期望 有著不同立場\n我從小證明 自己不用被體諒\n在我來的地方 要更強的臂膀\n我愛著我的父母 全村的希望\n\n擁有不同 everything I got totally earn it\n沒有放過任何機會 I’m gonna kill it\n善待身邊的人我能做到問心無愧\n我相信誠實的心才能得到真的富貴 ", grade: 2.0, music: "shou-zi-e-so-bo-fu-bo-fu-official-music-video", pic: "伯父"),
    Songs(song_name: "太陽", signer: "瘦子Ｅ.SO", lyrics: "已經習慣在家被你寵\n永遠都念著我\n早上拉開窗簾你不讓我睡過頭\n最好吃最可口\n是你做獅子頭\n用錢買不到你為我燙平的領口\n你的存在像應該\n但現在你不在\n我必須自己下廚吃我自己挾的菜\n沒什麼事我只想知道你那還習慣\n你告訴我比自己想的還要更勇敢\n\n在同個空間\n卻又感覺離的遠\n抱不到你的黑夜\n漫長冬天\n心臟被寒風攻陷\n害怕那是多直接\n\n在同個空間\n卻又感覺離的遠\n抱不到你的黑夜\n漫長冬天\n心臟被寒風攻陷\n害怕那是多直接\n\n太陽還不出來\n快悶壞 快悶壞 快悶壞 只想出門曬曬\nEverything gon’be fine\n在這等著你回來\n\n最後悔的是我們不能吻別\nLike we used to\n視訊裡的樣子你臉瘦的像個骷髏\n只想說輕鬆的 需要一點城府\n在這寒冷的城市我感覺像小人物\n他們說人在面臨難關 自私會變得更大\n我不介意你傷害我 我知道你也害怕\n如果我不能原諒你 等於我跟著踐踏\n如果不能在一起 至少有著相同盼望\n\n一堆唱片歌頌悲情 我說不動\n我自認自己活在光明 但敵不過\nI thought I was chilling not anymore\n誰會聽到哭聲 還能裝做沒疑惑\n頭上這片烏雲\n不能把我\n希望帶走\n雙膝跪地主阿指引路的盡頭\n我赴湯蹈火\n祢的愛應該是不分你我\n不分人種\n當愛人有一天變成戰友 親愛的不能軟弱\n", grade: 1.0, music: "shou-zi-e-so-tai-yang-when-the-cloudless-day-comes-lyric-video", pic: "太陽")]

    let Eric_songs = [
        Songs(song_name: "怎麼了", signer: "周興哲", lyrics: "你說藍色是你最愛的顏色\n你說如果沒有愛那又如何\n怎麼了 你怎麼了\n看過你曾經最燦爛的笑容\n看過你緊緊擁抱愛的面孔\n怎麼了 你消失了\n\n是不是我錯了 搞錯了 天灰了\n雨下著 凝望著 你走了\n都回不去了 像從前快樂\n\n怎麼能輕易說要結束\n怎麼會讓你抱著我哭\n太努力的我們最後用力給祝福\n怎麼看你笑著 我卻心如刀割\n\n原來我們都一樣頑固\n怎麼會誰都絕口不提要幸福\n再也不能牽著你走未來每一步\n我們懷念什麼 失去愛那一刻 才曉得\n\n你說藍色是你最愛的顏色\n你說如果沒有愛那又如何\n怎麼了 你怎麼了\n看過你曾經最燦爛的笑容\n看過你緊緊擁抱愛的面孔\n怎麼了 你消失了\n\n是不是我錯了 搞錯了 越愛著\n越痛著 苦笑著 你走了\n我們約好了 要比我快樂\n\n怎麼能輕易說要結束\n怎麼會讓你抱著我哭\n太努力的我們最後用力給祝福\n祝福我最愛的 遇見更愛你的 飛翔著\n\n我不想說 你不會懂 請別可憐我\n受傷的我 究竟需要 一個人 多少年 去度過\n我不想說 你不會懂 請別可憐我\n誰說我一定要永遠笑著 我不想", grade: 5.0, music: "hua-ju-ni-you-nian-da-xue-ma-pian-wei-qu", pic: "怎麼了"),
        Songs(song_name: "以後別做朋友", signer: "周興哲", lyrics: "習慣聽你分享生活細節\n害怕破壞完美的平衡點\n保持著距離一顆心的遙遠\n我的寂寞你就聽不見\n\n 我走回從前你往未來飛\n遇見對的人錯過交叉點\n明明你就已經站在我面前\n我卻不斷揮手說再見\n\n以後別做朋友 朋友不能牽手\n想愛你的衝動 我只能笑著帶過\n最好的朋友 有些夢 不能說出口\n就不用承擔 會失去你的心痛\n\n劃一個安全的天空界線\n誰都不准為我們掉眼淚\n放棄好好愛一個人的機會\n要看著你幸福到永遠\n\n以後別做朋友 朋友不能牽手\n想愛你的衝動 我只能笑著帶過\n最好的朋友 有些夢 不能說出口\n就不用承擔 會失去你的心痛\n\n忍住失控 太折磨 我自作自受\n回憶都是我 好不了的傷口\n\n以後還是朋友 還是你最懂我\n我們有始有終 就走到世界盡頭\n永遠的朋友 祝福我 遇見愛以後\n不會再懦弱 緊緊握住那雙手", grade: 4.0, music: "ericzhou-xing-zhe-yi-hou-bie-zuo-peng-you-the-distance-of-love-official-music-video", pic: "以後別做朋友"),
        Songs(song_name: "你好不好", signer: "周興哲", lyrics: "是不是 還那麼愛遲到\n熬夜工作又睡不好\n等你完成你的目標\n要戒掉逞強的嗜好\n\n都怪我把自尊放太高\n沒有把你照顧好\n驕傲 是脆弱的外表\n最怕我的心你不要\n\n能不能繼續 對我哭 對我笑 對我好\n繼續讓我 為你想 為你瘋 陪你老\n你好不好 好想知道\n別急著把回憶都丟掉\n\n我只需要你 在身邊 陪我吵 陪我鬧\n用好的我 把過去 壞的我 都換掉\n好想聽到 你堅決說愛我\n可惜回不去那一秒\n你好不好\n\n天知道 我快要受不了\n後悔鑽進心裡燒\n擁抱 再多一次就好\n你要的我都做得到\n\n能不能繼續 對我哭 對我笑 對我好\n繼續讓我 為你想 為你瘋 陪你老\n給你的好 還要不要\n答案我卻不敢揭曉", grade: 3.0, music: "ericzhou-xing-zhe-ni-hao-bu-hao-how-have-you-been-official-music-video-yi-han-pin-tu-pian-wei-qu", pic: "你好不好"),
        Songs(song_name: "終於了解自由", signer: "周興哲", lyrics: "春天的花相對\n終於看到了彼此的美\n漸漸的輕輕被風吹\n默默的愛上這滋味\n\n燦爛的笑相對\n會讓人漸漸放下防備\n你曾經說過要永遠\n但如今已無法還原\n\n好多話留在你身邊\n我已不需要留戀\n好多花再美再耀眼\n會終究枯謝\n\n我終於了解自由\n不是都是心碎了後才懂\n是安靜的時候\n是沒有人守候\n也不需要任何人在身等候\n\n我終於了解你我\n是最美麗的擦肩而過\n沒有了你的我\n還是一樣灑脫\n如果有一天再遇見你時候\n我會微笑點頭\n\n燦爛的笑相對\n會讓人漸漸放下防備\n你曾經說過要永遠\n但如今已無法還原\n\n好多話留在你身邊\n我已不需要留戀\n好多花再美再耀眼\n會終究枯謝\n\n我終於了解自由\n不是都是心碎了後才懂\n是安靜的時候\n是沒有人守候\n也不需要任何人在身等候\n\n我終於了解你我\n是最美麗的擦肩而過\n沒有了你的我\n還是一樣灑脫\n如果有一天再遇見你時候\n\n流過的淚都無所謂\n學著體會 愛的狼狽\n我們之間誰錯誰對已無所謂", grade: 2.0, music: "ericzhou-xing-zhe-zhong-yu-liao-jie-zi-you-freedom-official-music-video", pic: "自由"),
        Songs(song_name: "我很快樂", signer: "周興哲", lyrics: "雷雨依舊 奔跑著\n世界像你 模糊停格\n總以為能 永遠愛著\n時間 卻幫我們上了一課\n\n路 無法倒退\n我 錯過機會\n\n我說著 我很快樂 我無所謂\n你最懂我的 為你付出 我不後悔\n只要你過得好 我不一定 需要擁有\n你說要自由 我沒理由 不讓你走\n\n說真的 我很快樂 為你流淚\n你找到你的 幸福快樂 就不浪費\n要犯過多少錯 終於懂得 愛是什麼\n遺憾有多好 愛過的人忘不掉\n\n越努力愛 一個人\n越想割捨 越捨不得\n總以為能 失而復得\n你卻 有更好的未來等著\n\n我 一定成全\n我 微笑告別\n\n說真的 我很快樂 為你流淚\n你找到你的 幸福快樂 就不浪費\n要犯過多少錯 終於懂得 愛是什麼\n遺憾有多好 愛過的人忘不掉\n\n我說著 我很快樂 我無所謂\n你最懂我的 為你付出 我不後悔\n只要你過得好 我不一定 需要擁有\n你說要自由 我沒理由 不讓你走\n\n說真的 我很快樂 為你流淚\n你找到你的 幸福快樂 就不浪費\n多幸運能遇到 最懷念的 你的擁抱\n遺憾有多好 愛過的人忘不掉", grade: 1.0, music: "ericzhou-xing-zhe-wo-hen-kuai-le-im-happy-official-music-video", pic: "我很快樂")
    ]
